### ISSUE TITLE
Access outside of Baidu?

### ISSUE THREAD

**Issue by oliver-batchelor** [YuhuaXu/StereoDataset#2]
Is it possible to access some other way?

I can't create an account, if I try to sign up with a New Zealand phone number it always says:
"您当前的操作存在安全风险，请稍后再试"

**Comment by YuhuaXu** [comment]
You can download the dataset from OneDrive link now: 
https://1drv.ms/u/s!AhORN5PjOtgJgQVku2DVLD8Xaqkk?e=9DTd0n
https://1drv.ms/u/s!AoQcUQo52MO6aFIMqKJKDmzCxuQ?e=D8G0zi

**Comment by oliver-batchelor** [comment]
Thanks! That is awesome.

**Comment by mswattad** [comment]
The first link is not working
